/*
 * Configuration Data
 * Hilton Chat Widget
 */

// Available Fonts
export const fontsList = [
  "Inter", "Roboto", "Montserrat", "Poppins", "Oswald", "Rubik", "Ubuntu", "Exo 2",
  "Work Sans", "Fira Sans", "Anton", "Nunito", "Manrope", "Mulish", "Titillium Web",
  "PT Sans", "Bebas Neue", "Abril Fatface", "Lobster", "Righteous", "Russo One",
  "Permanent Marker", "Fjalla One", "Asap", "Cairo"
].sort();

// Available Icons
export const iconsList = [
  {
    id: 'chat',
    svg: '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>'
  },
  {
    id: 'message-circle',
    svg: '<path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>'
  },
  {
    id: 'custom-logo',
    svg: '<path fill-rule="evenodd" clip-rule="evenodd" d="M106.13 53.03c22.55,2.08 40.65,19.52 43.75,41.75l-96.58 0c3.18,-22.75 22.05,-40.47 45.33,-41.87l0 -4.17 -2.36 0c-2.32,0 -4.23,-1.91 -4.23,-4.23l0 0c0,-2.33 1.91,-4.23 4.23,-4.23l12.4 0c2.33,0 4.23,1.9 4.23,4.23l0 0c0,2.32 -1.9,4.23 -4.23,4.23l-2.54 0 0 4.29zm15.16 63.75c1.5,-1.94 4.29,-2.3 6.23,-0.8 1.94,1.5 2.3,4.29 0.8,6.23 -3.14,4.07 -7.19,7.4 -11.86,9.7 -4.51,2.21 -9.56,3.46 -14.87,3.46 -5.31,0 -10.36,-1.25 -14.87,-3.46 -4.67,-2.3 -8.72,-5.63 -11.86,-9.7 -1.5,-1.94 -1.14,-4.73 0.8,-6.23 1.94,-1.5 4.73,-1.14 6.23,0.8 2.33,3.01 5.31,5.47 8.74,7.15 3.28,1.62 7,2.52 10.96,2.52 3.96,0 7.68,-0.9 10.96,-2.52 3.43,-1.68 6.41,-4.14 8.74,-7.15zm-10.04 39.85c-1.68,1.41 -4.25,2.17 -4.31,-1.17 -0.02,-0.99 -0.04,-1.26 -0.06,-2.26 -0.81,-2.45 -3.2,-2.84 -5.68,-2.84l0 -0.01c-25.76,-0.2 -46.76,-20.38 -48.29,-45.8l97.36 0c-0.71,11.75 -5.05,23.66 -13.15,30.44l-25.87 21.64z"/>',
    viewBox: '0 0 203.18 203.18',
    fill: 'currentColor',
    stroke: 'none',
    size: '44'
  },
  {
    id: 'robot',
    svg: '<path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/>'
  },
  {
    id: 'star',
    svg: '<path d="M12 2L14.5 9.5 22 12 14.5 14.5 12 22 9.5 14.5 2 12 9.5 9.5 12 2z"/>'
  }
];

// Available Languages
export const languagesList = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' }
];

// Translations
export const translations = {
  en: {
    buttonText: "Chat with Hotel",
    placeholder: "Type a message...",
    welcome: "Hello! Welcome to our hotel. How can I help you with your reservation?",
    defaultAI: "Sorry, I am still learning. Can I help you book a room?",
    specialBooking: "Special Booking",
    language: "Language",
    confirmBooking: "Confirm Booking",
    editDetails: "Edit Details",
    personalOffer: "Personal Offer",
    selectedForYou: "Selected specially for you",
    dates: "Dates",
    guests: "Guests",
    total: "Total",
    consideredWishes: "Considered wishes",
    checkingAvailability: "Checking room availability...",
    analyzingNeeds: "Analyzing your needs...",
    finalizingDetails: "Finalizing details...",
    generatingOffer: "Generating personal offer...",
    newChat: "New Chat"
  },
  zh: {
    buttonText: "与酒店聊天",
    placeholder: "输入消息...",
    welcome: "您好！欢迎来到我们的酒店。我能帮您预订吗？",
    defaultAI: "抱歉，我还在学习中。我可以帮您预订房间吗？",
    specialBooking: "特别预订",
    language: "语言",
    confirmBooking: "确认预订",
    editDetails: "编辑详情",
    personalOffer: "个人优惠",
    selectedForYou: "为您精心挑选",
    dates: "日期",
    guests: "客人",
    total: "总计",
    consideredWishes: "已考虑的愿望",
    checkingAvailability: "正在检查房间可用性...",
    analyzingNeeds: "正在分析您的需求...",
    finalizingDetails: "正在最终确定细节...",
    generatingOffer: "正在生成个人优惠...",
    newChat: "新聊天"
  },
  hi: {
    buttonText: "होटल से चैट करें",
    placeholder: "संदेश लिखें...",
    welcome: "नमस्ते! हमारे होटल में आपका स्वागत है। मैं आपकी बुकिंग में कैसे मदद कर सकता हूं?",
    defaultAI: "क्षमा करें, मैं अभी सीख रहा हूं। क्या मैं आपको कमरा बुक करने में मदद कर सकता हूं?",
    specialBooking: "विशेष बुकिंग",
    language: "भाषा",
    confirmBooking: "बुकिंग की पुष्टि करें",
    editDetails: "विवरण संपादित करें",
    personalOffer: "व्यक्तिगत प्रस्ताव",
    selectedForYou: "आपके लिए विशेष रूप से चुना गया",
    dates: "तिथियां",
    guests: "मेहमान",
    total: "कुल",
    consideredWishes: "विचारित इच्छाएं",
    checkingAvailability: "कमरे की उपलब्धता जांच रहे हैं...",
    analyzingNeeds: "आपकी जरूरतों का विश्लेषण कर रहे हैं...",
    finalizingDetails: "अंतिम विवरण तैयार कर रहे हैं...",
    generatingOffer: "व्यक्तिगत प्रस्ताव तैयार कर रहे हैं...",
    newChat: "नई बातचीत"
  },
  es: {
    buttonText: "Chat con el Hotel",
    placeholder: "Escribe un mensaje...",
    welcome: "¡Hola! Bienvenido a nuestro hotel. ¿Cómo puedo ayudarte con tu reserva?",
    defaultAI: "Lo siento, todavía estoy aprendiendo. ¿Puedo ayudarte a reservar una habitación?",
    specialBooking: "Reserva Especial",
    language: "Idioma",
    confirmBooking: "Confirmar Reserva",
    editDetails: "Editar Detalles",
    personalOffer: "Oferta Personal",
    selectedForYou: "Seleccionado especialmente para ti",
    dates: "Fechas",
    guests: "Huéspedes",
    total: "Total",
    consideredWishes: "Deseos considerados",
    checkingAvailability: "Verificando disponibilidad...",
    analyzingNeeds: "Analizando tus necesidades...",
    finalizingDetails: "Finalizando detalles...",
    generatingOffer: "Generando oferta personal...",
    newChat: "Nueva conversación"
  },
  ar: {
    buttonText: "الدردشة مع الفندق",
    placeholder: "اكتب رسالة...",
    welcome: "مرحباً! أهلاً بك في فندقنا. كيف يمكنني مساعدتك في حجزك؟",
    defaultAI: "عذراً، ما زلت أتعلم. هل يمكنني مساعدتك في حجز غرفة؟",
    specialBooking: "حجز خاص",
    language: "اللغة",
    confirmBooking: "تأكيد الحجز",
    editDetails: "تعديل التفاصيل",
    personalOffer: "عرض شخصي",
    selectedForYou: "مختار خصيصاً لك",
    dates: "التواريخ",
    guests: "الضيوف",
    total: "المجموع",
    consideredWishes: "الرغبات المأخوذة بالاعتبار",
    checkingAvailability: "جاري التحقق من توفر الغرف...",
    analyzingNeeds: "جاري تحليل احتياجاتك...",
    finalizingDetails: "جاري إنهاء التفاصيل...",
    generatingOffer: "جاري إنشاء العرض الشخصي...",
    newChat: "محادثة جديدة"
  },
  fr: {
    buttonText: "Chat avec l'Hôtel",
    placeholder: "Écrivez un message...",
    welcome: "Bonjour! Bienvenue dans notre hôtel. Comment puis-je vous aider avec votre réservation?",
    defaultAI: "Désolé, je suis encore en apprentissage. Puis-je vous aider à réserver une chambre?",
    specialBooking: "Réservation Spéciale",
    language: "Langue",
    confirmBooking: "Confirmer la Réservation",
    editDetails: "Modifier les Détails",
    personalOffer: "Offre Personnelle",
    selectedForYou: "Sélectionné spécialement pour vous",
    dates: "Dates",
    guests: "Invités",
    total: "Total",
    consideredWishes: "Souhaits pris en compte",
    checkingAvailability: "Vérification de la disponibilité...",
    analyzingNeeds: "Analyse de vos besoins...",
    finalizingDetails: "Finalisation des détails...",
    generatingOffer: "Génération de l'offre personnelle...",
    newChat: "Nouvelle discussion"
  },
  bn: {
    buttonText: "হোটেলের সাথে চ্যাট করুন",
    placeholder: "একটি বার্তা লিখুন...",
    welcome: "হ্যালো! আমাদের হোটেলে স্বাগতম। আমি কিভাবে আপনার বুকিংয়ে সাহায্য করতে পারি?",
    defaultAI: "দুঃখিত, আমি এখনও শিখছি। আমি কি আপনাকে একটি রুম বুক করতে সাহায্য করতে পারি?",
    specialBooking: "বিশেষ বুকিং",
    language: "ভাষা",
    confirmBooking: "বুকিং নিশ্চিত করুন",
    editDetails: "বিবরণ সম্পাদনা করুন",
    personalOffer: "ব্যক্তিগত অফার",
    selectedForYou: "আপনার জন্য বিশেষভাবে নির্বাচিত",
    dates: "তারিখ",
    guests: "অতিথি",
    total: "মোট",
    consideredWishes: "বিবেচিত ইচ্ছা",
    checkingAvailability: "রুমের প্রাপ্যতা পরীক্ষা করা হচ্ছে...",
    analyzingNeeds: "আপনার চাহিদা বিশ্লেষণ করা হচ্ছে...",
    finalizingDetails: "চূড়ান্ত বিবরণ তৈরি করা হচ্ছে...",
    generatingOffer: "ব্যক্তিগত অফার তৈরি করা হচ্ছে...",
    newChat: "নতুন চ্যাট"
  },
  pt: {
    buttonText: "Chat com o Hotel",
    placeholder: "Digite uma mensagem...",
    welcome: "Olá! Bem-vindo ao nosso hotel. Como posso ajudá-lo com sua reserva?",
    defaultAI: "Desculpe, ainda estou aprendendo. Posso ajudá-lo a reservar um quarto?",
    specialBooking: "Reserva Especial",
    language: "Idioma",
    confirmBooking: "Confirmar Reserva",
    editDetails: "Editar Detalhes",
    personalOffer: "Oferta Pessoal",
    selectedForYou: "Selecionado especialmente para você",
    dates: "Datas",
    guests: "Hóspedes",
    total: "Total",
    consideredWishes: "Desejos considerados",
    checkingAvailability: "Verificando disponibilidade...",
    analyzingNeeds: "Analisando suas necessidades...",
    finalizingDetails: "Finalizando detalhes...",
    generatingOffer: "Gerando oferta pessoal...",
    newChat: "Novo chat"
  },
  ru: {
    buttonText: "Чат с отелем",
    placeholder: "Напишите сообщение...",
    welcome: "Здравствуйте! Добро пожаловать в наш отель. Чем могу помочь с вашим бронированием?",
    defaultAI: "Извините, я пока учусь. Могу ли я помочь вам забронировать номер?",
    specialBooking: "Особое бронирование",
    language: "Язык",
    confirmBooking: "Подтвердить бронирование",
    editDetails: "Изменить детали",
    personalOffer: "Персональное предложение",
    selectedForYou: "Подобрано специально для вас",
    dates: "Даты",
    guests: "Гости",
    total: "Итого",
    consideredWishes: "Учтённые пожелания",
    checkingAvailability: "Проверяем доступность номеров...",
    analyzingNeeds: "Учитываем ваши потребности...",
    finalizingDetails: "Уточняем финальные детали...",
    generatingOffer: "Формируем персональное предложение...",
    newChat: "Новый чат"
  },
  id: {
    buttonText: "Chat dengan Hotel",
    placeholder: "Ketik pesan...",
    welcome: "Halo! Selamat datang di hotel kami. Bagaimana saya bisa membantu dengan reservasi Anda?",
    defaultAI: "Maaf, saya masih belajar. Bisakah saya membantu Anda memesan kamar?",
    specialBooking: "Pemesanan Khusus",
    language: "Bahasa",
    confirmBooking: "Konfirmasi Pemesanan",
    editDetails: "Edit Detail",
    personalOffer: "Penawaran Pribadi",
    selectedForYou: "Dipilih khusus untuk Anda",
    dates: "Tanggal",
    guests: "Tamu",
    total: "Total",
    consideredWishes: "Keinginan yang dipertimbangkan",
    checkingAvailability: "Memeriksa ketersediaan kamar...",
    analyzingNeeds: "Menganalisis kebutuhan Anda...",
    finalizingDetails: "Menyelesaikan detail...",
    generatingOffer: "Membuat penawaran pribadi...",
    newChat: "Obrolan Baru"
  },
  // Legacy support for Ukrainian
  ua: {
    buttonText: "Чат з готелем",
    placeholder: "Напишіть повідомлення...",
    welcome: "Вітаємо! Ласкаво просимо до нашого готелю. Чим можу допомогти з вашим бронюванням?",
    defaultAI: "Вибачте, я поки що вчуся. Чи можу я допомогти вам забронювати номер?",
    specialBooking: "Особливе бронювання",
    language: "Мова",
    confirmBooking: "Підтвердити бронювання",
    editDetails: "Змінити деталі",
    personalOffer: "Персональна пропозиція",
    selectedForYou: "Підібрано спеціально для вас",
    dates: "Дати",
    guests: "Гості",
    total: "Всього",
    consideredWishes: "Враховані побажання",
    checkingAvailability: "Перевіряємо доступність номерів...",
    analyzingNeeds: "Враховуємо ваші потреби...",
    finalizingDetails: "Уточнюємо фінальні деталі...",
    generatingOffer: "Формуємо персональну пропозицію...",
    newChat: "Новий чат"
  }
};
