/*
 * Configuration Data
 * Hilton Chat Widget
 */

// Available Fonts
export const fontsList = [
  "Inter", "Roboto", "Montserrat", "Poppins", "Oswald", "Rubik", "Ubuntu", "Exo 2",
  "Work Sans", "Fira Sans", "Anton", "Nunito", "Manrope", "Mulish", "Titillium Web",
  "PT Sans", "Bebas Neue", "Abril Fatface", "Lobster", "Righteous", "Russo One",
  "Permanent Marker", "Fjalla One", "Asap", "Cairo"
].sort();

// Available Icons
export const iconsList = [
  {
    id: 'chat',
    svg: '<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>'
  },
  {
    id: 'message-circle',
    svg: '<path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"></path>'
  },
  {
    id: 'custom-logo',
    svg: '<path fill-rule="evenodd" clip-rule="evenodd" d="M106.13 53.03c22.55,2.08 40.65,19.52 43.75,41.75l-96.58 0c3.18,-22.75 22.05,-40.47 45.33,-41.87l0 -4.17 -2.36 0c-2.32,0 -4.23,-1.91 -4.23,-4.23l0 0c0,-2.33 1.91,-4.23 4.23,-4.23l12.4 0c2.33,0 4.23,1.9 4.23,4.23l0 0c0,2.32 -1.9,4.23 -4.23,4.23l-2.54 0 0 4.29zm15.16 63.75c1.5,-1.94 4.29,-2.3 6.23,-0.8 1.94,1.5 2.3,4.29 0.8,6.23 -3.14,4.07 -7.19,7.4 -11.86,9.7 -4.51,2.21 -9.56,3.46 -14.87,3.46 -5.31,0 -10.36,-1.25 -14.87,-3.46 -4.67,-2.3 -8.72,-5.63 -11.86,-9.7 -1.5,-1.94 -1.14,-4.73 0.8,-6.23 1.94,-1.5 4.73,-1.14 6.23,0.8 2.33,3.01 5.31,5.47 8.74,7.15 3.28,1.62 7,2.52 10.96,2.52 3.96,0 7.68,-0.9 10.96,-2.52 3.43,-1.68 6.41,-4.14 8.74,-7.15zm-10.04 39.85c-1.68,1.41 -4.25,2.17 -4.31,-1.17 -0.02,-0.99 -0.04,-1.26 -0.06,-2.26 -0.81,-2.45 -3.2,-2.84 -5.68,-2.84l0 -0.01c-25.76,-0.2 -46.76,-20.38 -48.29,-45.8l97.36 0c-0.71,11.75 -5.05,23.66 -13.15,30.44l-25.87 21.64z"/>',
    viewBox: '0 0 203.18 203.18',
    fill: 'currentColor',
    stroke: 'none',
    size: '44'
  },
  {
    id: 'robot',
    svg: '<path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/>'
  },
  {
    id: 'star',
    svg: '<path d="M12 2L14.5 9.5 22 12 14.5 14.5 12 22 9.5 14.5 2 12 9.5 9.5 12 2z"/>'
  }
];

// Available Languages
export const languagesList = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'id', name: 'Indonesian', nativeName: 'Indonesia', flag: '🇮🇩' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' }
];

// Translations
export const translations = {
  en: {
    buttonText: "Chat with Hotel",
    placeholder: "Type a message...",
    welcome: "Want to book a room? I'll help you find the perfect option! 😊",
    defaultAI: "Sorry, I am still learning. Can I help you book a room?",
    language: "Language",
    confirmBooking: "Confirm Booking",
    editDetails: "Edit Details",
    personalOffer: "Personal Offer",
    selectedForYou: "Selected specially for you",
    dates: "Dates",
    guests: "Guests",
    total: "Total",
    consideredWishes: "Considered wishes",
    checkingAvailability: "Checking room availability...",
    analyzingNeeds: "Analyzing your needs...",
    finalizingDetails: "Finalizing details...",
    generatingOffer: "Generating personal offer...",
    newChat: "New Chat",
    contactManager: "Manager",
    online: "Online",
    allHotels: "All hotels",
    cityName: "Kyiv",
    changeCity: "Change city",
    downloadApp: "Download App",
    searchingSpecialist: "Searching for a specialist...",
    menu: "Menu",
    close: "Close",
    roomDetails: "Room details",
    night: "night",
    reviews: "Reviews",
    book: "Book",
    askQuestion: "Ask a question",
    viewPhotos: "View photos",
    serviceDetails: "Service details",
    historyTitle: "Dialog history",
    searchDialogs: "Search dialogs...",
    noDialogs: "No saved dialogs",
    back: "Back",
    soundOn: "On",
    soundOff: "Off",
    newMessages: "New messages",
    scrollDown: "Scroll to bottom",
    roomArea: "Area",
    continueChat: "Continue chat",
    escalateTitle: "Switch to manager?",
    escalateDesc: "Your request requires a specialist",
    escalateNote: "The manager will receive a notification and contact you shortly",
    escalateConfirm: "Yes, connect",
    cancel: "Cancel",
    resetConfirmTitle: "Start new chat?",
    resetConfirmDesc: "Current chat history will be saved in dialog history",
    resetConfirmSubmit: "Start",
    resetConfirmCancel: "Cancel",
    tgConfirmTitle: "Do you want to continue?",
    tgConfirmDesc: "You will be redirected to the external Telegram app",
    tgConfirmProceed: "Continue",
    smsConfirmationTitle: "SMS Confirmation",
    smsCodePlaceholder: "SMS Code",
    confirm: "Confirm",
    loginSuccessTitle: "Logged in successfully",
    loginSuccessDesc: "Now you can continue using the chat",
    excellent: "Excellent",
    policyConsentPrefix: "By starting a chat you agree to",
    userAgreement: "Terms of Use",
    and: "and",
    privacyPolicy: "Privacy Policy",
    goToTelegram: "Go to Telegram",
    fasterConvenient: "Faster and more convenient",
    voiceInput: "Voice input",
    send: "Send",
    document: "Document",
    restaurantMenu: "Restaurant Menu",
    rooms: "Rooms",
    services: "Services",
    previousDialogs: "Previous Dialogs",
    notificationSound: "Notification Sound",
    selectLanguageTitle: "Select Language",
    selectLanguageDesc: "Choose language for the interface",
    personalGuestCard: "Personal Guest Card",
    getInTelegram: "Get in Telegram",
    goToApp: "Go to App",
    newChat: "New Chat",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    weekdays: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
    roomModalTitleNew: "New Room",
    roomModalTitleEdit: "Edit Room",
    hotel: "Hotel",
    selectHotel: "Select Hotel",
    roomName: "Room Name",
    roomNamePlaceholder: "e.g. Panorama Suite",
    roomDescription: "Description",
    roomDescriptionPlaceholder: "Detailed room description...",
    areaSqM: "Area (m²)",
    pricePerNightLabel: "Price per night ($)",
    mainPhoto: "Main Photo",
    clickToUpload: "Click to upload",
    galleryPhotos: "Gallery Photos",
    add: "Add",
    askQuestionToggle: '"Ask Question" Button',
    marketing: "Marketing",
    badge: "Badge",
    noBadge: "No Badge",
    roomsLeft: "Rooms left (0 = do not show)",
    discountPercentage: "Discount (%)",
    oldPrice: "Old price ($)",
    reviewsLabel: "Reviews",
    addReview: "Add Review",
    guestName: "Guest Name",
    reviewTextPlaceholder: "Review text...",
    availabilityCalendar: "Availability Calendar",
    generate: "Generate",
    available: "Available",
    booked: "Booked",
    save: "Save",
    noHotel: "No Hotel",
    night1: "night",
    nights2: "nights",
    nights5: "nights",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    statusCompleted: "Completed",
    onRequest: "On request",
    fixed: "Fixed",
    perHour: "hour",
    perDay: "day",
    categorySpa: "SPA & Wellness",
    categoryRestaurant: "Restaurant",
    categoryTransport: "Transfer",
    categoryEntertainment: "Entertainment",
    categoryBusiness: "Business",
    categoryKids: "For Kids",
    categoryOther: "Other",
    roomDeleteConfirm: "Delete this room?",
    roomNameRequired: "Please enter room name",
    serviceDeleteConfirm: "Delete this service?",
    serviceNameRequired: "Please enter service name",
    reviewFieldsRequired: "Please fill all review fields",
    noReviews: "No reviews",
    bookingsEmpty: "No bookings",
    bookingSearchNoResults: "Nothing found for your search",
    bookingGenerateTestDesc: 'Click "Test" to generate demo data',
    bookingCancelConfirm: "Cancel booking for {name}?",
    bookingDeleteConfirm: "Delete booking for {name} forever?\nThis action cannot be undone.",
    bookingEditConfirm: "Editing booking for {name}\n\nCurrent data:\n• Check-in: {checkIn}\n• Check-out: {checkOut}\n• Room: {room}\n• Guests: {guests}\n\nTo edit booking:\n1. Current booking will be cancelled\n2. Guest will be able to create a new booking through chat\n\nContinue?",
    bookingCancelledAlert: "Booking cancelled.\n\nNow guest {name} can create a new booking through chat with updated data.",
    addTestBookingsConfirm: "There are already bookings in the database. Add more test data?",
    testBookingsGeneratedAlert: "Generated {count} test bookings!\n\nExamples of guests for testing cancellation:\n• {names}\n\nYou can find bookings through search by name.",
    noServices: "No services. Click 'Add'.",
    serviceModalTitleNew: "New Service",
    serviceModalTitleEdit: "Edit Service",
    serviceName: "Service Name",
    serviceNamePlaceholder: "e.g. SPA massage",
    serviceDescription: "Description",
    serviceDescriptionPlaceholder: "Detailed service description...",
    priceUsd: "Price ($)",
    priceType: "Price Type",
    category: "Category",
    addBookingToggle: '"Add to booking" Button',
    propertyModalTitle: "Edit Hotel",
    propertyName: "Hotel Name",
    propertyNamePlaceholder: "e.g. Hilton Center",
    logoLabel: "Logo (shown in chat header)",
    uploadLogo: "Upload Logo",
    propertyDescription: "Hotel Description (for LLM)",
    propertyDescriptionPlaceholder: "What the hotel has...",
    baseCurrency: "Base Currency",
    hotelPhoto: "Hotel Photo",
    uploadPhoto: "Upload Photo",
    cityGeo: "City (GEO)",
    cityGeoPlaceholder: "London, Dubai, Paris...",
    countryGeo: "Country (GEO)",
    countryGeoPlaceholder: "UK, UAE...",
    tagsLabel: "Discovery Tags (comma separated)",
    ratingStars: "Rating (Stars)",
    minPricePerNight: "Min price per night",
    multiPropertySearch: "Multi-property search participation",
    showInShortlist: "Show in Shortlist",
    additionalServices: "Additional Services",
    noPhoto: "No photo",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet.",
    serviceQuestionTowels: 'What exactly should I bring? Bath towels 🛁, bathrobes or extra pillows/blankets?',
    serviceQuestionCleaning: 'When is it convenient for you? I can arrange cleaning right now or at a time that suits you.',
    serviceQuestionMinibar: 'What exactly should be replenished — drinks, snacks or a full update of the entire mini-bar?',
    serviceLabelTowels: 'Bring towels',
    serviceLabelCleaning: 'Room cleaning',
    serviceLabelMinibar: 'Minibar replenishment',
    serviceTimeTowels: '10–15 minutes',
    serviceTimeCleaning: '15–25 minutes',
    serviceTimeMinibar: '10–20 minutes',
    taskCreated: 'Task created',
    expectedTime: 'Expected time'
  },
  zh: {
    buttonText: "与酒店聊天",
    placeholder: "输入消息...",
    welcome: "想预订房间吗？我来帮您找到最佳选择！😊",
    defaultAI: "抱歉，我还在学习中。我可以帮您预订房间吗？",
    language: "语言",
    confirmBooking: "确认预订",
    editDetails: "编辑详情",
    personalOffer: "个人优惠",
    selectedForYou: "为您精心挑选",
    dates: "日期",
    guests: "客人",
    total: "总计",
    consideredWishes: "已考虑的愿望",
    checkingAvailability: "正在检查房间可用性...",
    analyzingNeeds: "正在分析您的需求...",
    finalizingDetails: "正在最终确定细节...",
    generatingOffer: "正在生成个人优惠...",
    newChat: "新聊天",
    contactManager: "经理",
    policyConsentPrefix: "开始聊天即表示您同意",
    userAgreement: "使用条款",
    and: "和",
    privacyPolicy: "隐私政策",
    goToApp: "前往应用程序",
    downloadOnThe: "下载于",
    appStore: "App Store",
    getItOn: "获取于",
    googlePlay: "Google Play",
    chooseThisHotel: "选择这家酒店",
    fromPrice: "从",
    allHotelsIntro: "选择一家酒店以了解更多信息或开始预订。",
    noAdminHotels: "管理面板中尚无酒店。"
  },
  hi: {
    buttonText: "होटल से चैट करें",
    placeholder: "संदेश लिखें...",
    welcome: "क्या आप कमरा बुक करना चाहते हैं? मैं आपके लिए सबसे अच्छा विकल्प ढूंढूंगा! 😊",
    defaultAI: "क्षमा करें, मैं अभी सीख रहा हूं। क्या मैं आपको कमरा बुक करने में मदद कर सकता हूं?",
    language: "भाषा",
    confirmBooking: "बुकिंग की पुष्टि करें",
    editDetails: "विवरण संपादित करें",
    personalOffer: "व्यक्तिगत प्रस्ताव",
    selectedForYou: "आपके लिए विशेष रूप से चुना गया",
    dates: "तिथियां",
    guests: "मेहमान",
    total: "कुल",
    consideredWishes: "विचारित इच्छाएं",
    checkingAvailability: "कमरे की उपलब्धता जांच रहे हैं...",
    analyzingNeeds: "आपकी जरूरतों का विश्लेषण कर रहे हैं...",
    finalizingDetails: "अंतिम विवरण तैयार कर रहे हैं...",
    generatingOffer: "व्यक्तिगत प्रस्ताव तैयार कर रहे हैं...",
    newChat: "नई बातचीत",
    contactManager: "प्रबंधक",
    policyConsentPrefix: "चैट शुरू करके आप सहमत हैं",
    userAgreement: "उपयोग की शर्तें",
    and: "और",
    privacyPolicy: "गोपनीयता नीति",
    goToApp: "ऐप पर जाएं",
    downloadOnThe: "डाउनलोड करें",
    appStore: "App Store",
    getItOn: "पायें",
    googlePlay: "Google Play",
    chooseThisHotel: "यह होटल चुनें",
    fromPrice: "से ప్రారంభ",
    allHotelsIntro: "अधिक जानने या बुकिंग शुरू करने के लिए एक होटल चुनें।",
    noAdminHotels: "एडमिन पैनल में अभी तक कोई होटल नहीं है।"
  },
  es: {
    buttonText: "Chat con el Hotel",
    placeholder: "Escribe un mensaje...",
    welcome: "¿Quieres reservar una habitación? ¡Te ayudo a encontrar la mejor opción! 😊",
    defaultAI: "Lo siento, todavía estoy aprendiendo. ¿Puedo ayudarte a reservar una habitación?",
    language: "Idioma",
    confirmBooking: "Confirmar Reserva",
    editDetails: "Editar Detalles",
    personalOffer: "Oferta Personal",
    selectedForYou: "Seleccionado especialmente para ti",
    dates: "Fechas",
    guests: "Huéspedes",
    total: "Total",
    consideredWishes: "Deseos considerados",
    checkingAvailability: "Verificando disponibilidad...",
    analyzingNeeds: "Analizando tus necesidades...",
    finalizingDetails: "Finalizando detalles...",
    generatingOffer: "Generando oferta personal...",
    newChat: "Nueva conversación",
    contactManager: "Gerente",
    policyConsentPrefix: "Al iniciar un chat, aceptas los",
    userAgreement: "Términos de uso",
    and: "y la",
    privacyPolicy: "Política de privacidad",
    goToApp: "Ir a la app",
    downloadOnThe: "Consíguelo en el",
    appStore: "App Store",
    getItOn: "DISPONIBLE EN",
    googlePlay: "Google Play",
    chooseThisHotel: "Elegir este hotel",
    fromPrice: "desde",
    allHotelsIntro: "Elija un hotel para obtener más información o comenzar a reservar.",
    noAdminHotels: "Aún no hay hoteles en el panel de administración."
  },
  ar: {
    buttonText: "الدردشة مع الفندق",
    placeholder: "اكتب رسالة...",
    welcome: "هل تريد حجز غرفة؟ سأساعدك في إيجاد أفضل خيار! 😊",
    defaultAI: "عذراً، ما زلت أتعلم. هل يمكنني مساعدتك في حجز غرفة؟",
    language: "اللغة",
    confirmBooking: "تأكيد الحجز",
    editDetails: "تعديل التفاصيل",
    personalOffer: "عرض شخصي",
    selectedForYou: "مختار خصيصاً لك",
    dates: "التواريخ",
    guests: "الضيوف",
    total: "المجموع",
    consideredWishes: "الرغبات المأخوذة بالاعتبار",
    checkingAvailability: "جاري التحقق من توفر الغرف...",
    analyzingNeeds: "جاري تحليل احتياجاتك...",
    finalizingDetails: "جاري إنهاء التفاصيل...",
    generatingOffer: "جاري إنشاء العرض الشخصي...",
    newChat: "محادثة جديدة",
    contactManager: "مدير",
    policyConsentPrefix: "ببدء الدردشة فإنك توافق على",
    userAgreement: "شروط الاستخدام",
    and: "و",
    privacyPolicy: "سياسة الخصوصية",
    goToApp: "الذهاب إلى التطبيق",
    downloadOnThe: "تنزيل من",
    appStore: "App Store",
    getItOn: "احصل عليه من",
    googlePlay: "Google Play",
    chooseThisHotel: "اختر هذا الفندق",
    fromPrice: "من",
    allHotelsIntro: "اختر فندقًا لمعرفة المزيد أو بدء الحجز.",
    noAdminHotels: "لا توجد فنادق في لوحة الإدارة بعد."
  },
  fr: {
    buttonText: "Chat avec l'Hôtel",
    placeholder: "Écrivez un message...",
    welcome: "Vous souhaitez réserver une chambre ? Je vous aide à trouver la meilleure option ! 😊",
    defaultAI: "Désolé, je suis encore en apprentissage. Puis-je vous aider à réserver une chambre?",
    language: "Langue",
    confirmBooking: "Confirmer la Réservation",
    editDetails: "Modifier les Détails",
    personalOffer: "Offre Personnelle",
    selectedForYou: "Sélectionné spécialement pour vous",
    dates: "Dates",
    guests: "Invités",
    total: "Total",
    consideredWishes: "Souhaits pris en compte",
    checkingAvailability: "Vérification de la disponibilité...",
    analyzingNeeds: "Analyse de vos besoins...",
    finalizingDetails: "Finalisation des détails...",
    generatingOffer: "Génération de l'offre personnelle...",
    newChat: "Nouvelle discussion",
    contactManager: "Directeur",
    policyConsentPrefix: "En commençant une discussion, vous acceptez les",
    userAgreement: "Conditions d'utilisation",
    and: "et la",
    privacyPolicy: "Politique de confidentialité",
    goToApp: "Aller à l'app",
    downloadOnThe: "Télécharger dans l'",
    appStore: "App Store",
    getItOn: "DISPONIBLE SUR",
    googlePlay: "Google Play",
    chooseThisHotel: "Choisir cet hôtel",
    fromPrice: "à partir de",
    allHotelsIntro: "Choisissez un hôtel pour en savoir plus ou commencer à réserver.",
    noAdminHotels: "Il n'y a pas encore d'hôtels"
  },
  bn: {
    buttonText: "হোটেলের সাথে চ্যাট করুন",
    placeholder: "একটি বার্তা লিখুন...",
    welcome: "একটি রুম বুক করতে চান? আমি আপনার জন্য সেরা বিকল্পটি খুঁজে পেতে সাহায্য করব! 😊",
    defaultAI: "দুঃখিত, আমি এখনও শিখছি। আমি কি আপনাকে একটি রুম বুক করতে সাহায্য করতে পারি?",
    language: "ভাষা",
    confirmBooking: "বুকিং নিশ্চিত করুন",
    editDetails: "বিবরণ সম্পাদনা করুন",
    personalOffer: "ব্যক্তিগত অফার",
    selectedForYou: "আপনার জন্য বিশেষভাবে নির্বাচিত",
    dates: "তারিখ",
    guests: "অতিথি",
    total: "মোট",
    consideredWishes: "বিবেচিত ইচ্ছা",
    checkingAvailability: "রুমের প্রাপ্যতা পরীক্ষা করা হচ্ছে...",
    analyzingNeeds: "আপনার চাহিদা বিশ্লেষণ করা হচ্ছে...",
    finalizingDetails: "চূড়ান্ত বিবরণ তৈরি করা হচ্ছে...",
    generatingOffer: "ব্যক্তিগত অফার তৈরি করা হচ্ছে...",
    newChat: "নতুন চ্যাট",
    contactManager: "ম্যানেজার",
    policyConsentPrefix: "চ্যাট শুরু করার মাধ্যমে আপনি সম্মত হচ্ছেন",
    userAgreement: "ব্যবহারের শর্তাবলী",
    and: "এবং",
    privacyPolicy: "গোপনীয়তা নীতি",
    goToApp: "অ্যাপে যান",
    downloadOnThe: "ডাউনলোড করুন",
    appStore: "App Store",
    getItOn: "এখান থেকে পান",
    googlePlay: "Google Play",
    chooseThisHotel: "এই হোটেলটি বেছে নিন",
    fromPrice: "থেকে",
    allHotelsIntro: "আরও জানতে অথবা বুকিং শুরু করতে একটি হোটেল বেছে নিন।",
    noAdminHotels: "অ্যাডমিন প্যানেলে এখনও কোনো হোটেল নেই।"
  },
  pt: {
    buttonText: "Chat com o Hotel",
    placeholder: "Digite uma mensagem...",
    welcome: "Quer reservar um quarto? Vou ajudá-lo a encontrar a melhor opção! 😊",
    defaultAI: "Desculpe, ainda estou aprendendo. Posso ajudá-lo a reservar um quarto?",
    language: "Idioma",
    confirmBooking: "Confirmar Reserva",
    editDetails: "Editar Detalhes",
    personalOffer: "Oferta Pessoal",
    selectedForYou: "Selecionado especialmente para você",
    dates: "Datas",
    guests: "Hóspedes",
    total: "Total",
    consideredWishes: "Desejos considerados",
    checkingAvailability: "Verificando disponibilidade...",
    analyzingNeeds: "Analisando suas necessidades...",
    finalizingDetails: "Finalizando detalhes...",
    generatingOffer: "Gerando oferta pessoal...",
    newChat: "Novo chat",
    contactManager: "Gerente",
    policyConsentPrefix: "Ao iniciar um chat, você concorda com os",
    userAgreement: "Termos de Uso",
    and: "e a",
    privacyPolicy: "Política de Privacidade",
    goToApp: "Ir para o app",
    downloadOnThe: "Baixar na",
    appStore: "App Store",
    getItOn: "DISPONÍVEL NO",
    googlePlay: "Google Play",
    chooseThisHotel: "Escolher este hotel",
    fromPrice: "a partir de",
    allHotelsIntro: "Escolha um hotel para saber mais ou iniciar a reserva.",
    noAdminHotels: "Ainda não há hotéis no painel de administração."
  },
  ru: {
    buttonText: "Чат с отелем",
    placeholder: "Напишите сообщение...",
    welcome: "Хотите забронировать номер? Помогу подобрать лучший вариант! 😊",
    defaultAI: "Извините, я пока учусь. Могу ли я помочь вам забронировать номер?",
    language: "Язык",
    confirmBooking: "Подтвердить бронирование",
    editDetails: "Изменить детали",
    personalOffer: "Персональное предложение",
    selectedForYou: "Подобрано специально для вас",
    dates: "Даты",
    guests: "Гости",
    total: "Итого",
    consideredWishes: "Учтённые пожелания",
    checkingAvailability: "Проверяем доступность номеров...",
    analyzingNeeds: "Учитываем ваши потребности...",
    finalizingDetails: "Уточняем финальные детали...",
    generatingOffer: "Формируем персональное предложение...",
    newChat: "Новый чат",
    contactManager: "Менеджер",
    online: "Онлайн",
    allHotels: "Все отели",
    cityName: "Киев",
    changeCity: "Сменить город",
    downloadApp: "Скачать приложение",
    searchingSpecialist: "Ищем специалиста...",
    menu: "Меню",
    close: "Закрыть",
    roomDetails: "Детали номера",
    night: "ночь",
    reviews: "Отзывы",
    book: "Забронировать",
    askQuestion: "Задать вопрос",
    viewPhotos: "Просмотреть фото",
    serviceDetails: "Детали услуги",
    historyTitle: "История диалогов",
    searchDialogs: "Поиск по диалогам...",
    noDialogs: "Нет сохраненных диалогов",
    back: "Назад",
    soundOn: "Вкл",
    soundOff: "Выкл",
    newMessages: "Новые сообщения",
    scrollDown: "Прокрутить вниз",
    roomArea: "Площадь",
    continueChat: "Продолжить чат",
    escalateTitle: "Переключить на менеджера?",
    escalateDesc: "Ваш запрос требует участия специалиста",
    escalateNote: "Менеджер получит уведомление и свяжется с вами в ближайшее время",
    escalateConfirm: "Да, соединить",
    cancel: "Отмена",
    resetConfirmTitle: "Начать новый чат?",
    resetConfirmDesc: "Текущая история чата будет сохранена в истории диалогов",
    resetConfirmSubmit: "Начать",
    resetConfirmCancel: "Отмена",
    tgConfirmTitle: "Вы хотите продолжить?",
    tgConfirmDesc: "Вы будете перенаправлены во внешнее приложение Telegram",
    tgConfirmProceed: "Продолжить",
    smsConfirmationTitle: "Подтверждение по SMS",
    smsCodePlaceholder: "Код из SMS",
    confirm: "Подтвердить",
    loginSuccessTitle: "Вы успешно вошли в свой аккаунт",
    loginSuccessDesc: "Теперь вы можете продолжить использование чата",
    excellent: "Отлично",
    policyConsentPrefix: "Начиная чат вы соглашаетесь с",
    userAgreement: "Условиями использования",
    and: "и",
    privacyPolicy: "Политикой конфиденциальности",
    goToTelegram: "Перейти в Telegram",
    fasterConvenient: "Быстрее и удобнее",
    voiceInput: "Голосовой ввод",
    send: "Отправить",
    document: "Документ",
    restaurantMenu: "Меню ресторана",
    rooms: "Номера",
    services: "Услуги",
    previousDialogs: "История диалогов",
    notificationSound: "Звук уведомлений",
    selectLanguageTitle: "Выберите язык",
    selectLanguageDesc: "Выберите язык для интерфейса",
    personalGuestCard: "Персональная карточка гостя",
    getInTelegram: "Получить в Telegram",
    goToApp: "Перейти в приложение",
    newChat: "Новый чат",
    months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
    weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
    roomModalTitleNew: "Новый номер",
    roomModalTitleEdit: "Редактировать номер",
    hotel: "Отель",
    selectHotel: "Выберите отель",
    roomName: "Название номера",
    roomNamePlaceholder: "Например: Люкс Панорама",
    roomDescription: "Описание",
    roomDescriptionPlaceholder: "Детальное описание номера...",
    areaSqM: "Площадь (м²)",
    pricePerNightLabel: "Цена за ночь ($)",
    mainPhoto: "Главное фото",
    clickToUpload: "Нажмите для загрузки",
    galleryPhotos: "Галерея фото",
    add: "Добавить",
    askQuestionToggle: 'Кнопка "Задать вопрос"',
    marketing: "Маркетинг",
    badge: "Бейдж",
    noBadge: "Без бейджа",
    roomsLeft: "Осталось номеров (0 = не показывать)",
    discountPercentage: "Скидка (%)",
    oldPrice: "Старая цена ($)",
    reviewsLabel: "Отзывы",
    addReview: "Добавить отзыв",
    guestName: "Имя гостя",
    reviewTextPlaceholder: "Текст отзыва...",
    availabilityCalendar: "Календарь доступности",
    generate: "Сгенерировать",
    available: "Свободно",
    booked: "Занято",
    save: "Сохранить",
    noHotel: "Без отеля",
    night1: "ночь",
    nights2: "ночи",
    nights5: "ночей",
    statusConfirmed: "Подтверждено",
    statusCancelled: "Отменено",
    statusCompleted: "Завершено",
    onRequest: "По запросу",
    fixed: "Фиксированная",
    perHour: "час",
    perDay: "день",
    categorySpa: "SPA & Wellness",
    categoryRestaurant: "Ресторан",
    categoryTransport: "Трансфер",
    categoryEntertainment: "Развлечения",
    categoryBusiness: "Бизнес",
    categoryKids: "Для детей",
    categoryOther: "Другое",
    roomDeleteConfirm: "Удалить этот номер?",
    roomNameRequired: "Введите название номера",
    serviceDeleteConfirm: "Удалить эту услугу?",
    serviceNameRequired: "Введите название услуги",
    reviewFieldsRequired: "Пожалуйста, заполните все поля отзыва",
    noReviews: "Нет отзывов",
    bookingsEmpty: "Нет бронирований",
    bookingSearchNoResults: "Ничего не найдено по вашему запросу",
    bookingGenerateTestDesc: 'Нажмите "Тестовые" для генерации демо-данных',
    bookingCancelConfirm: "Отменить бронирование для {name}?",
    bookingDeleteConfirm: "Удалить бронирование для {name} навсегда?\nЭто действие нельзя отменить.",
    bookingEditConfirm: "Редактирование бронирования для {name}\n\nТекущие данные:\n• Заезд: {checkIn}\n• Выезд: {checkOut}\n• Номер: {room}\n• Гостей: {guests}\n\nДля редактирования бронирования:\n1. Текущее бронирование будет отменено\n2. Гость сможет создать новое бронирование через чат\n\nПродолжить?",
    bookingCancelledAlert: "Бронирование отменено.\n\nТеперь гость {name} может создать новое бронирование через чат с обновленными данными.",
    addTestBookingsConfirm: "В базе уже есть бронирования. Добавить еще тестовые данные?",
    testBookingsGeneratedAlert: "Сгенерировано {count} тестовых бронирований!\n\nПримеры гостей для тестирования отмены:\n• {names}\n\nВы можете найти бронирование через поиск по имени.",
    noServices: "Нет услуг. Нажмите 'Добавить'.",
    serviceModalTitleNew: "Новая услуга",
    serviceModalTitleEdit: "Редактировать услугу",
    serviceName: "Название услуги",
    serviceNamePlaceholder: "Например: SPA массаж",
    serviceDescription: "Описание",
    serviceDescriptionPlaceholder: "Детальное описание услуги...",
    priceUsd: "Цена ($)",
    priceType: "Тип цены",
    category: "Категория",
    addBookingToggle: 'Кнопка "Добавить к бронированию"',
    propertyModalTitle: "Редактировать отель",
    propertyName: "Название отеля",
    propertyNamePlaceholder: "Например: Hilton Center",
    logoLabel: "Логотип (показывается в шапке чату)",
    uploadLogo: "Загрузить логотип",
    propertyDescription: "Описание отеля (для LLM)",
    propertyDescriptionPlaceholder: "Описание, что есть в отеле...",
    baseCurrency: "Базовая валюта",
    hotelPhoto: "Фото отеля",
    uploadPhoto: "Загрузить фото",
    cityGeo: "Город (GEO)",
    cityGeoPlaceholder: "Москва, Дубай, Париж...",
    countryGeo: "Страна (GEO)",
    countryGeoPlaceholder: "Россия, ОАЭ...",
    tagsLabel: "Discovery Теги (через запятую)",
    ratingStars: "Рейтинг (Звезды)",
    minPricePerNight: "Мин. цена за ночь",
    multiPropertySearch: "Участие в multi-property поиске",
    showInShortlist: "Показывать в Shortlist",
    additionalServices: "Дополнительные услуги",
    noPhoto: "Нет фото",
    downloadOnThe: "Скачать в",
    appStore: "App Store",
    getItOn: "Скачать в",
    googlePlay: "Google Play",
    chooseThisHotel: "Выбрать этот отель",
    fromPrice: "от",
    allHotelsIntro: "Выберите отель, чтобы узнать больше или начать бронирование.",
    noAdminHotels: "В административной панели еще нет ни одного отеля.",
    serviceQuestionTowels: 'Что именно принести? Банные полотенца 🛁, халаты или дополнительные подушки/одеяла?',
    serviceQuestionCleaning: 'Когда вам удобно? Могу организовать уборку прямо сейчас или в удобное для вас время.',
    serviceQuestionMinibar: 'Что именно пополнить — напитки, снеки или полностью обновить весь мини-бар?',
    serviceLabelTowels: 'Принести полотенца',
    serviceLabelCleaning: 'Уборка номера',
    serviceLabelMinibar: 'Пополнение мини-бара',
    serviceTimeTowels: '10–15 минут',
    serviceTimeCleaning: '15–25 минут',
    serviceTimeMinibar: '10–20 минут',
    taskCreated: 'Задача создана',
    expectedTime: 'Ожидаемое время'
  },
  id: {
    buttonText: "Chat dengan Hotel",
    placeholder: "Ketik pesan...",
    welcome: "Ingin memesan kamar? Saya akan membantu Anda menemukan pilihan terbaik! 😊",
    defaultAI: "Maaf, saya masih belajar. Bisakah saya membantu Anda memesan kamar?",
    language: "Bahasa",
    confirmBooking: "Konfirmasi Pemesanan",
    editDetails: "Edit Detail",
    personalOffer: "Penawaran Pribadi",
    selectedForYou: "Dipilih khusus untuk Anda",
    dates: "Tanggal",
    guests: "Tamu",
    total: "Total",
    consideredWishes: "Keinginan yang dipertimbangkan",
    checkingAvailability: "Memeriksa ketersediaan kamar...",
    analyzingNeeds: "Menganalisis kebutuhan Anda...",
    finalizingDetails: "Menyelesaikan detail...",
    generatingOffer: "Membuat penawaran pribadi...",
    newChat: "Obrolan Baru",
    contactManager: "Manajer",
    policyConsentPrefix: "Dengan memulai obrolan, Anda menyetujui",
    userAgreement: "Syarat Penggunaan",
    and: "dan",
    privacyPolicy: "Kebijakan Privasi",
    goToApp: "Buka Ke Aplikasi",
    downloadOnThe: "Unduh di",
    appStore: "App Store",
    getItOn: "DAPATKAN DI",
    googlePlay: "Google Play",
    chooseThisHotel: "Pilih hotel ini",
    fromPrice: "mulai dari",
    allHotelsIntro: "Pilih hotel untuk mempelajari lebih lanjut atau mulai memesan.",
    noAdminHotels: "Belum ada hotel di panel admin."
  },
  uk: {
    buttonText: "Чат з готелем",
    placeholder: "Напишіть повідомлення...",
    welcome: "Хочете забронювати номер? Допоможу підібрати найкращий варіант! 😊",
    defaultAI: "Вибачте, я поки що вчуся. Чи можу я допомогти вам забронювати номер?",
    language: "Мова",
    confirmBooking: "Підтвердити бронювання",
    editDetails: "Змінити деталі",
    personalOffer: "Персональна пропозиція",
    selectedForYou: "Підібрано спеціально для вас",
    dates: "Дати",
    guests: "Гості",
    total: "Всього",
    consideredWishes: "Враховані побажання",
    checkingAvailability: "Перевіряємо доступність номерів...",
    analyzingNeeds: "Враховуємо ваші потреби...",
    finalizingDetails: "Уточнюємо фінальні деталі...",
    generatingOffer: "Формуємо персональну пропозицію...",
    newChat: "Новий чат",
    contactManager: "Менеджер",
    online: "Онлайн",
    allHotels: "Всі готелі",
    cityName: "Київ",
    changeCity: "Змінити місто",
    downloadApp: "Завантажити додаток",
    searchingSpecialist: "Шукаємо фахівця...",
    menu: "Меню",
    close: "Закрити",
    roomDetails: "Деталі номера",
    night: "ніч",
    reviews: "Відгуки",
    book: "Забронювати",
    askQuestion: "Задати питання",
    viewPhotos: "Переглянути фото",
    serviceDetails: "Деталі послуги",
    historyTitle: "Історія діалогів",
    searchDialogs: "Пошук по діалогах...",
    noDialogs: "Немає збережених діалогів",
    back: "Назад",
    soundOn: "Увімк",
    soundOff: "Вимк",
    newMessages: "Нові повідомлення",
    scrollDown: "Прокрутити вниз",
    roomArea: "Площа",
    continueChat: "Продовжити чат",
    escalateTitle: "Переключити на менеджера?",
    escalateDesc: "Ваш запит потребує участі фахівця",
    escalateNote: "Менеджер отримає повідомлення і зв'яжеться з вами найближчим часом",
    escalateConfirm: "Так, з'єднати",
    cancel: "Скасувати",
    resetConfirmTitle: "Почати новий чат?",
    resetConfirmDesc: "Поточну історію чату буде збережено в історії діалогів",
    resetConfirmSubmit: "Почати",
    resetConfirmCancel: "Скасувати",
    tgConfirmTitle: "Ви хочете продовжити?",
    tgConfirmDesc: "Ви будете перенаправлені у зовнішній додаток Telegram",
    tgConfirmProceed: "Продовжити",
    smsConfirmationTitle: "Підтвердження по SMS",
    smsCodePlaceholder: "Код з SMS",
    confirm: "Підтвердити",
    loginSuccessTitle: "Ви успішно увійшли у свій акаунт",
    loginSuccessDesc: "Тепер ви можете продовжити використання чату",
    excellent: "Чудово",
    policyConsentPrefix: "Починаючи чат ви погоджуєтесь з",
    userAgreement: "Умовами використання",
    and: "та",
    privacyPolicy: "Політикою конфіденційності",
    goToTelegram: "Перейти в Telegram",
    fasterConvenient: "Швидше та зручніше",
    voiceInput: "Голосове введення",
    send: "Надіслати",
    document: "Документ",
    restaurantMenu: "Меню ресторану",
    rooms: "Номери",
    services: "Послуги",
    previousDialogs: "Попередні діалоги",
    notificationSound: "Звук сповіщень",
    selectLanguageTitle: "Оберіть мову",
    selectLanguageDesc: "Оберіть мову для інтерфейсу",
    personalGuestCard: "Персональна картка гостя",
    getInTelegram: "Отримати в Telegram",
    goToApp: "Перейти в додаток",
    months: ["Січень", "Лютий", "Березень", "Квітень", "Травень", "Червень", "Липень", "Серпень", "Вересень", "Жовтень", "Листопад", "Грудень"],
    weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
    roomModalTitleNew: "Новий номер",
    roomModalTitleEdit: "Редагувати номер",
    hotel: "Готель",
    selectHotel: "Оберіть готель",
    roomName: "Назва номера",
    roomNamePlaceholder: "Наприклад: Люкс Панорама",
    roomDescription: "Опис",
    roomDescriptionPlaceholder: "Детальний опис номера...",
    areaSqM: "Площа (м²)",
    pricePerNightLabel: "Ціна за ніч ($)",
    mainPhoto: "Головне фото",
    clickToUpload: "Натисніть для завантаження",
    galleryPhotos: "Галерея фото",
    add: "Додати",
    askQuestionToggle: 'Кнопка "Задати питання"',
    marketing: "Маркетинг",
    badge: "Бейдж",
    noBadge: "Без бейджа",
    roomsLeft: "Залишилось номерів (0 = не показувати)",
    discountPercentage: "Знижка (%)",
    oldPrice: "Стара ціна ($)",
    reviewsLabel: "Відгуки",
    addReview: "Додати відгук",
    guestName: "Ім'я гостя",
    reviewTextPlaceholder: "Текст відгуку...",
    availabilityCalendar: "Календар доступності",
    generate: "Згенерувати",
    available: "Вільно",
    booked: "Зайнято",
    save: "Зберегти",
    noHotel: "Без готелю",
    night1: "ніч",
    nights2: "ночі",
    nights5: "ночей",
    statusConfirmed: "Підтверджено",
    statusCancelled: "Скасовано",
    statusCompleted: "Завершено",
    onRequest: "За запитом",
    fixed: "Фіксована",
    perHour: "год",
    perDay: "день",
    categorySpa: "SPA & Wellness",
    categoryRestaurant: "Ресторан",
    categoryTransport: "Трансфер",
    categoryEntertainment: "Розваги",
    categoryBusiness: "Бізнес",
    categoryKids: "Для дітей",
    categoryOther: "Інше",
    roomDeleteConfirm: "Видалити цей номер?",
    roomNameRequired: "Введіть назву номера",
    serviceDeleteConfirm: "Видалити цю послугу?",
    serviceNameRequired: "Введіть назву послуги",
    reviewFieldsRequired: "Будь ласка, заповніть всі поля відгуку",
    noReviews: "Немає відгуків",
    bookingsEmpty: "Немає бронювань",
    bookingSearchNoResults: "Нічого не знайдено за вашим запитом",
    bookingGenerateTestDesc: 'Натисніть "Тестові" для генерації демо-даних',
    bookingCancelConfirm: "Скасувати бронювання для {name}?",
    bookingDeleteConfirm: "Видалити бронювання для {name} назавжди?\nЦю дію неможливо скасувати.",
    bookingEditConfirm: "Редагування бронювання для {name}\n\nПоточні дані:\n• Заїзд: {checkIn}\n• Виїзд: {checkOut}\n• Номер: {room}\n• Гостей: {guests}\n\nДля редагування бронювання:\n1. Поточне бронювання буде скасовано\n2. Гість зможе створити нове бронювання через чат\n\nПродовжити?",
    bookingCancelledAlert: "Бронювання скасовано.\n\nТепер гість {name} може створити нове бронювання через чат з оновленими даними.",
    addTestBookingsConfirm: "Вже є бронювання в базі. Додати ще тестові дані?",
    testBookingsGeneratedAlert: "Згенеровано {count} тестових бронювань!\n\nПриклади гостей для тестування скасування:\n• {names}\n\nВи можете знайти бронювання через пошук за ПІБ.",
    noServices: "Немає послуг. Натисніть «Додати».",
    serviceModalTitleNew: "Нова послуга",
    serviceModalTitleEdit: "Редагувати послугу",
    serviceName: "Назва послуги",
    serviceNamePlaceholder: "Наприклад: SPA масаж",
    serviceDescription: "Опис",
    serviceDescriptionPlaceholder: "Детальний опис послуги...",
    priceUsd: "Ціна ($)",
    priceType: "Тип ціни",
    category: "Категорія",
    addBookingToggle: 'Кнопка "Додати до бронювання"',
    propertyModalTitle: "Редагувати готель",
    propertyName: "Назва готелю",
    propertyNamePlaceholder: "Наприклад: Hilton Center",
    logoLabel: "Логотип (показується в шапці чату)",
    downloadOnThe: "Завантажити в",
    appStore: "App Store",
    getItOn: "Завантажити з",
    googlePlay: "Google Play",
    uploadLogo: "Завантажити логотип",
    propertyDescription: "Опис готелю (для LLM)",
    propertyDescriptionPlaceholder: "Опис, що є в готелі...",
    baseCurrency: "Базова валюта",
    hotelPhoto: "Фото готелю",
    uploadPhoto: "Завантажити фото",
    cityGeo: "Місто (GEO)",
    cityGeoPlaceholder: "Київ, Дубай, Париж...",
    countryGeo: "Країна (GEO)",
    countryGeoPlaceholder: "Україна, ОАЕ...",
    tagsLabel: "Discovery Теги (через кому)",
    ratingStars: "Рейтинг (Зірки)",
    minPricePerNight: "Мін. ціна за ніч",
    multiPropertySearch: "Участь у multi-property пошуку",
    showInShortlist: "Показувати в Shortlist",
    additionalServices: "Додаткові послуги",
    noPhoto: "Немає фото",
    chooseThisHotel: "Обрати цей готель",
    fromPrice: "від",
    allHotelsIntro: "Оберіть готель, щоб дізнатися більше або розпочати бронювання.",
    noAdminHotels: "В адміністративній панелі ще немає жодного готелю.",
    serviceQuestionTowels: 'Що саме принести? Банні рушники 🛁, халати або додаткові подушки/ковдри?',
    serviceQuestionCleaning: 'Коли вам зручно? Можу організувати прибирання прямо зараз або у зручний для вас час.',
    serviceQuestionMinibar: 'Що саме поповнити — напої, снеки або повністю оновити весь міні-бар?',
    serviceLabelTowels: 'Принести рушники',
    serviceLabelCleaning: 'Прибирання номера',
    serviceLabelMinibar: 'Поповнення міні-бару',
    serviceTimeTowels: '10–15 хвилин',
    serviceTimeCleaning: '15–25 хвилин',
    serviceTimeMinibar: '10–20 хвилин',
    taskCreated: 'Завдання створено',
    expectedTime: 'Очікуваний час'
  },
  de: {
    buttonText: "Chat mit Hotel",
    placeholder: "Nachricht eingeben...",
    welcome: "Möchten Sie ein Zimmer buchen? Ich helfe Ihnen, die beste Option zu finden! 😊",
    defaultAI: "Entschuldigung, ich lerne noch. Kann ich Ihnen helfen, ein Zimmer zu buchen?",
    language: "Sprache",
    confirmBooking: "Buchung bestätigen",
    editDetails: "Details bearbeiten",
    personalOffer: "Persönliches Angebot",
    selectedForYou: "Speziell für Sie ausgewählt",
    dates: "Termine",
    guests: "Gäste",
    total: "Gesamt",
    consideredWishes: "Berücksichtigte Wünsche",
    checkingAvailability: "Verfügbarkeit prüfen...",
    analyzingNeeds: "Ihre Bedürfnisse analysieren...",
    finalizingDetails: "Details finalisieren...",
    generatingOffer: "Persönliches Angebot erstellen...",
    newChat: "Neuer Chat",
    policyConsentPrefix: "Mit dem Start eines Chats erklären Sie sich mit den",
    userAgreement: "Nutzungsbedingungen",
    and: "und der",
    privacyPolicy: "Datenschutzerklärung einverstanden",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet.",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  ja: {
    buttonText: "ホテルとチャット",
    placeholder: "メッセージを入力...",
    welcome: "お部屋のご予約をご希望ですか？最適なプランをご提案します！ 😊",
    defaultAI: "申し訳ございませんが、まだ学習中です。お部屋の予約をお手伝いできますか？",
    language: "言語",
    confirmBooking: "予約を確認",
    editDetails: "詳細を編集",
    personalOffer: "個人オファー",
    selectedForYou: "特別に選ばれました",
    dates: "日付",
    guests: "ゲスト",
    total: "合計",
    consideredWishes: "考慮された希望",
    checkingAvailability: "空室状況を確認中...",
    analyzingNeeds: "ニーズを分析中...",
    finalizingDetails: "詳細を確定中...",
    generatingOffer: "個人オファーを作成中...",
    newChat: "新しいチャット",
    contactManager: "マネージャー",
    goToApp: "アプリに移動",
    downloadOnThe: "ダウンロード:",
    appStore: "App Store",
    getItOn: "で手に入れよう",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  ko: {
    buttonText: "호텔과 채팅",
    placeholder: "메시지 입력...",
    welcome: "객실을 예약하시겠어요? 최고의 옵션을 찾아드리겠습니다! 😊",
    defaultAI: "죄송합니다. 아직 배우는 중입니다. 객실 예약을 도와드릴까요?",
    language: "언어",
    confirmBooking: "예약 확인",
    editDetails: "세부 정보 편집",
    personalOffer: "개인 제안",
    selectedForYou: "특별히 선택되었습니다",
    dates: "날짜",
    guests: "손님",
    total: "총액",
    consideredWishes: "고려된 소망",
    checkingAvailability: "객실 가능 여부 확인 중...",
    analyzingNeeds: "귀하의 필요 분석 중...",
    finalizingDetails: "세부 사항 마무리 중...",
    generatingOffer: "개인 제안 생성 중...",
    newChat: "새 채팅",
    contactManager: "매니저",
    goToApp: "앱으로 이동",
    downloadOnThe: "다운로드:",
    appStore: "App Store",
    getItOn: "다운로드:",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  it: {
    buttonText: "Chat con Hotel",
    placeholder: "Scrivi un messaggio...",
    welcome: "Vuoi prenotare una camera? Ti aiuto a trovare la migliore opzione! 😊",
    defaultAI: "Mi dispiace, sto ancora imparando. Posso aiutarti a prenotare una camera?",
    language: "Lingua",
    confirmBooking: "Conferma Prenotazione",
    editDetails: "Modifica Dettagli",
    personalOffer: "Offerta Personale",
    selectedForYou: "Selezionato appositamente per te",
    dates: "Date",
    guests: "Ospiti",
    total: "Totale",
    consideredWishes: "Desideri considerati",
    checkingAvailability: "Verifica disponibilità...",
    analyzingNeeds: "Analisi delle tue esigenze...",
    finalizingDetails: "Finalizzazione dettagli...",
    generatingOffer: "Creazione offerta personale...",
    newChat: "Nuova chat",
    contactManager: "Manager",
    goToApp: "Vai all'App",
    downloadOnThe: "Scarica su",
    appStore: "App Store",
    getItOn: "DISPONIBILE SU",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  tr: {
    buttonText: "Otel ile Sohbet",
    placeholder: "Mesaj yazın...",
    welcome: "Bir oda rezervasyonu yapmak ister misiniz? En iyi seçeneği bulmanıza yardımcı olayım! 😊",
    defaultAI: "Üzgünüm, hala öğreniyorum. Oda rezervasyonu yapmanızda yardımcı olabilir miyim?",
    language: "Dil",
    confirmBooking: "Rezervasyonu Onayla",
    editDetails: "Detayları Düzenle",
    personalOffer: "Kişisel Teklif",
    selectedForYou: "Özel olarak sizin için seçildi",
    dates: "Tarihler",
    guests: "Misafirler",
    total: "Toplam",
    consideredWishes: "Dikkate alınan istekler",
    checkingAvailability: "Müsaitlik kontrol ediliyor...",
    analyzingNeeds: "İhtiyaçlarınız analiz ediliyor...",
    finalizingDetails: "Detaylar tamamlanıyor...",
    generatingOffer: "Kişisel teklif oluşturuluyor...",
    newChat: "Yeni sohbet",
    contactManager: "Yönetici",
    goToApp: "Uygulamaya Git",
    downloadOnThe: "Şuradan İndir:",
    appStore: "App Store",
    getItOn: "ŞURADAN ALIN",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet.",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  nl: {
    buttonText: "Chat met Hotel",
    placeholder: "Typ een bericht...",
    welcome: "Wilt u een kamer boeken? Ik help u de beste optie te vinden! 😊",
    defaultAI: "Sorry, ik ben nog aan het leren. Kan ik u helpen een kamer te boeken?",
    language: "Taal",
    confirmBooking: "Boeking Bevestigen",
    editDetails: "Details Bewerken",
    personalOffer: "Persoonlijk Aanbod",
    selectedForYou: "Speciaal voor u geselecteerd",
    dates: "Data",
    guests: "Gasten",
    total: "Totaal",
    consideredWishes: "Overwogen wensen",
    checkingAvailability: "Beschikbaarheid controleren...",
    analyzingNeeds: "Uw behoeften analyseren...",
    finalizingDetails: "Details afronden...",
    generatingOffer: "Persoonlijk aanbod maken...",
    newChat: "Nieuwe chat",
    contactManager: "Manager",
    goToApp: "Naar de App",
    downloadOnThe: "Download in de",
    appStore: "App Store",
    getItOn: "ONTDEK HET OP",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  pl: {
    buttonText: "Czat z Hotelem",
    placeholder: "Napisz wiadomość...",
    welcome: "Chcesz zarezerwować pokój? Pomogę znaleźć najlepszą opcję! 😊",
    defaultAI: "Przepraszam, wciąż się uczę. Czy mogę pomóc w rezerwacji pokoju?",
    language: "Język",
    confirmBooking: "Potwierdź Rezerwację",
    editDetails: "Edytuj Szczegóły",
    personalOffer: "Osobista Oferta",
    selectedForYou: "Specjalnie dla Ciebie wybrane",
    dates: "Daty",
    guests: "Goście",
    total: "Razem",
    consideredWishes: "Uwzględnione życzenia",
    checkingAvailability: "Sprawdzanie dostępności...",
    analyzingNeeds: "Analiza potrzeb...",
    finalizingDetails: "Finalizacja szczegółów...",
    generatingOffer: "Tworzenie osobistej oferty...",
    newChat: "Nowy czat",
    contactManager: "Menedżer",
    policyConsentPrefix: "Rozpoczynając czat, zgadzasz się na",
    userAgreement: "Warunki użytkowania",
    and: "i",
    privacyPolicy: "Politykę prywatności",
    goToApp: "Przejdź do aplikacji",
    downloadOnThe: "Pobierz w",
    appStore: "App Store",
    getItOn: "POBIERZ Z",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  vi: {
    buttonText: "Trò chuyện với Khách sạn",
    placeholder: "Nhập tin nhắn...",
    welcome: "Bạn muốn đặt phòng không? Tôi sẽ giúp bạn tìm lựa chọn tốt nhất! 😊",
    defaultAI: "Xin lỗi, tôi vẫn đang học. Tôi có thể giúp bạn đặt phòng không?",
    language: "Ngôn ngữ",
    confirmBooking: "Xác nhận Đặt phòng",
    editDetails: "Chỉnh sửa Chi tiết",
    personalOffer: "Ưu đãi Cá nhân",
    selectedForYou: "Được chọn đặc biệt cho bạn",
    dates: "Ngày",
    guests: "Khách",
    total: "Tổng cộng",
    consideredWishes: "Mong muốn được xem xét",
    checkingAvailability: "Đang kiểm tra tình trạng phòng...",
    analyzingNeeds: "Đang phân tích nhu cầu của bạn...",
    finalizingDetails: "Đang hoàn thiện chi tiết...",
    generatingOffer: "Đang tạo ưu đãi cá nhân...",
    newChat: "Trò chuyện mới",
    contactManager: "Quản lý",
    policyConsentPrefix: "Bằng cách bắt đầu trò chuyện, bạn đồng ý với",
    userAgreement: "Điều khoản sử dụng",
    and: "và",
    privacyPolicy: "Chính sách bảo mật",
    goToApp: "Đến Ứng dụng",
    downloadOnThe: "Tải xuống trên",
    appStore: "App Store",
    getItOn: "TẢI TRÊN",
    googlePlay: "Google Play",
    chooseThisHotel: "Choose this hotel",
    fromPrice: "from",
    allHotelsIntro: "Choose a hotel to learn more or start booking.",
    noAdminHotels: "There are no hotels in the admin panel yet."
  },
  th: {
    buttonText: "แชทกับโรงแรม",
    placeholder: "พิมพ์ข้อความ...",
    welcome: "ต้องการจองห้องพักไหม? ฉันจะช่วยหาตัวเลือกที่ดีที่สุดให้คุณ! 😊",
    defaultAI: "ขออภัย ฉันยังเรียนรู้อยู่ ฉันช่วยคุณจองห้องได้ไหม?",
    language: "ภาษา",
    confirmBooking: "ยืนยันการจอง",
    editDetails: "แก้ไขรายละเอียด",
    personalOffer: "ข้อเสนอส่วนตัว",
    selectedForYou: "เลือกพิเศษสำหรับคุณ",
    dates: "วันที่",
    guests: "แขก",
    total: "รวม",
    consideredWishes: "ความต้องการที่พิจารณา",
    checkingAvailability: "กำลังตรวจสอบห้องว่าง...",
    analyzingNeeds: "กำลังวิเคราะห์ความต้องการของคุณ...",
    finalizingDetails: "กำลังสรุปรายละเอียด...",
    generatingOffer: "กำลังสร้างข้อเสนอส่วนตัว...",
    newChat: "แชทใหม่",
    contactManager: "ผู้จัดการ",
    policyConsentPrefix: "การเริ่มแชทแสดงว่าคุณยอมรับ",
    userAgreement: "ข้อกำหนดการใช้งาน",
    and: "และ",
    privacyPolicy: "นโยบายความเป็นส่วนตัว",
    goToApp: "ไปที่แอป",
    downloadOnThe: "ดาวน์โหลดบน",
    appStore: "App Store",
    getItOn: "ดาวน์โหลดผ่าน",
    googlePlay: "Google Play"
  },
  // Legacy support for Ukrainian
  ua: {
    buttonText: "Чат з готелем",
    placeholder: "Напишіть повідомлення...",
    welcome: "Хочете забронювати номер? Допоможу підібрати найкращий варіант! 😊",
    defaultAI: "Вибачте, я поки що вчуся. Чи можу я допомогти вам забронювати номер?",
    language: "Мова",
    confirmBooking: "Підтвердити бронювання",
    editDetails: "Змінити деталі",
    personalOffer: "Персональна пропозиція",
    selectedForYou: "Підібрано спеціально для вас",
    dates: "Дати",
    guests: "Гості",
    total: "Всього",
    consideredWishes: "Враховані побажання",
    checkingAvailability: "Перевіряємо доступність номерів...",
    analyzingNeeds: "Враховуємо ваші потреби...",
    finalizingDetails: "Уточнюємо фінальні деталі...",
    generatingOffer: "Формуємо персональну пропозицію...",
    newChat: "Новий чат",
    policyConsentPrefix: "Починаючи чат ви погоджуєтесь з",
    userAgreement: "Умовами використання",
    and: "та",
    privacyPolicy: "Політикою конфіденційності",
    goToApp: "Перейти в додаток",
    downloadOnThe: "Завантажити в",
    appStore: "App Store",
    getItOn: "Завантажити з",
    googlePlay: "Google Play"
  }
};
